import os
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# -----------------------------
# Paths (edit if needed)
# -----------------------------
BASE_DIR = os.getcwd()
DATASET_DIR = os.path.join(BASE_DIR, "dataset", "room_acoustic_largedataset")
EDC_DIR = os.path.join(DATASET_DIR, "EDC")
FEATURE_CSV = os.path.join(DATASET_DIR, "roomFeaturesDataset.csv")
PREDICTIONS_FILE = "sample_predictions.npy"  # generated by your training code

# -----------------------------
# Load predictions
# -----------------------------
y_pred = np.load(PREDICTIONS_FILE)  # shape: (N, EDC_LEN)
print("Predictions shape:", y_pred.shape)

# Load feature CSV to get IDs of used samples
df = pd.read_csv(FEATURE_CSV)
if len(df) > y_pred.shape[0]:
    df = df.sample(n=y_pred.shape[0], random_state=42).reset_index(drop=True)
ids = df["ID"].tolist()

# -----------------------------
# Functions to compute room acoustics metrics
# -----------------------------
def edt(edc):
    """Early Decay Time (EDT) in seconds"""
    edc_db = 10 * np.log10(edc / np.max(edc) + 1e-12)
    idx_start = 0
    idx_end = np.where(edc_db <= -10)[0][0] if np.any(edc_db <= -10) else len(edc_db)-1
    slope = (edc_db[idx_end] - edc_db[idx_start]) / (idx_end)
    edt_time = -60 / slope if slope != 0 else 0
    return edt_time

def t20(edc):
    """T20 in seconds"""
    edc_db = 10 * np.log10(edc / np.max(edc) + 1e-12)
    idx_start = np.where(edc_db <= -5)[0][0] if np.any(edc_db <= -5) else 0
    idx_end = np.where(edc_db <= -25)[0][0] if np.any(edc_db <= -25) else len(edc_db)-1
    slope = (edc_db[idx_end] - edc_db[idx_start]) / (idx_end - idx_start + 1e-6)
    t20_time = -60 / slope if slope != 0 else 0
    return t20_time

def c50(edc):
    """Clarity C50 in dB"""
    early_energy = np.sum(edc[:int(0.05*len(edc))]**2)
    late_energy = np.sum(edc[int(0.05*len(edc)):]**2)
    c50_db = 10 * np.log10(early_energy / (late_energy + 1e-12))
    return c50_db

# -----------------------------
# Compute metrics
# -----------------------------
edt_pred, t20_pred, c50_pred = [], [], []
edt_true, t20_true, c50_true = [], [], []

for i, id_ in enumerate(ids):
    y_t = np.load(os.path.join(EDC_DIR, f"{id_}.npy"))
    y_p = y_pred[i]

    # Clip negative predictions to small positive value
    y_p = np.clip(y_p, 1e-12, None)

    edt_true.append(edt(y_t))
    t20_true.append(t20(y_t))
    c50_true.append(c50(y_t))

    edt_pred.append(edt(y_p))
    t20_pred.append(t20(y_p))
    c50_pred.append(c50(y_p))

# -----------------------------
# Compute MAE, RMSE, R²
# -----------------------------
def compute_metrics(y_true_list, y_pred_list):
    mae = mean_absolute_error(y_true_list, y_pred_list)
    rmse = np.sqrt(mean_squared_error(y_true_list, y_pred_list))
    r2 = r2_score(y_true_list, y_pred_list)
    return mae, rmse, r2

metrics = {}
metrics['EDT (s)'] = compute_metrics(edt_true, edt_pred)
metrics['T20 (s)'] = compute_metrics(t20_true, t20_pred)
metrics['C50 (dB)'] = compute_metrics(c50_true, c50_pred)

# -----------------------------
# Display results
# -----------------------------
print("\nModel Performance Compared to Project 1–5 (baseline):")
baseline = {
    "EDT (s)": (0.020, 0.02, 0.98),
    "T20 (s)": (0.020, 0.03, 0.98),
    "C50 (dB)": (0.90, 2, 0.98)
}

df_results = pd.DataFrame({
    "Metric": metrics.keys(),
    "MAE (yours)": [metrics[k][0] for k in metrics],
    "RMSE (yours)": [metrics[k][1] for k in metrics],
    "R² (yours)": [metrics[k][2] for k in metrics],
    "MAE (baseline)": [baseline[k][0] for k in metrics],
    "RMSE (baseline)": [baseline[k][1] for k in metrics],
    "R² (baseline)": [baseline[k][2] for k in metrics],
})

print(df_results.to_string(index=False))
